blind:   
# Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

   # Position Controllers of cambase joint
    1_wheel_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: 1_wheel_joint
      pid: {p: 1, i: 0.0, d: 0.0}

    2_wheel_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: 2_wheel_joint
      pid: {p: 1, i: 0.0, d: 0.0}
  

